export const SET_CURRENCY_LIST = 'SET_CURRENCY_LIST';
export const SET_CURRENCY_HISTORY = 'SET_CURRENCY_HISTORY';

export const SET_SELECTED_BASE_CURRENCY = 'SET_SELECTED_BASE_CURRENCY';
export const SET_SELECTED_TIME_INTERVAL = 'SET_SELECTED_TIME_INTERVAL';

export const UI_START_LOAD_CURRENCY_LIST = "UI_START_LOAD_CURRENCY_LIST";
export const UI_STOP_LOAD_CURRENCY_LIST = "UI_STOP_LOAD_CURRENCY_LIST";

export const UI_START_LOAD_CURRENCY_HISTORY = "UI_START_LOAD_CURRENCY_HISTORY";
export const UI_STOP_LOAD_CURRENCY_HISTORY = "UI_STOP_LOAD_CURRENCY_HISTORY";

export const UI_SET_IS_OFFLINE = "UI_SET_IS_OFFLINE";